export default {
	'en-AU': {
		'action.save': 'Save',
		'action.edit': 'Edit',
		'action.undo': 'Undo',
		'action.close': 'Close',
		'action.cancel': 'Cancel',
		'action.preview': 'Preview',
		'action.copy_id': 'Copy ID',
		'action.continue': 'Continue',
		'action.view_all': 'View all',
		'action.show_all': 'Show all',
		'action.lock_pin': 'Lock PIN',
		'action.copy_link': 'Copy Link',
		'action.learn_more': 'Learn More',
		'action.edit_studio': 'Edit in Studio',
		'action.view_roblox': 'View on Roblox',
		'action.view_talent': 'View on Talent Hub',
		'action.view_devforum': 'View on DevForum',
		'action.copy_place_id': 'Copy Place ID',
		'action.configure_place': 'Configure Place',
		'action.copy_universe_id': 'Copy Experience ID',
		'action.configure_universe': 'Configure Experience',

		'action.friend.0': 'Send Friend Request',
		'action.friend.1': 'Remove Friend',
		'action.friend.2': 'Friend Request Sent',
		'action.friend.3': 'Accept Friend Request',
		'action.friend.5': 'Decline Friend Request',

		'user_action.user.profile': 'Your Profile',
		'user_action.user.creations': 'Your Creations',
		'user_action.group': 'Your Primary Group',
		'user_action.settings.settings': 'Website Settings',
		'user_action.other.logout': 'Sign out',

		'home': 'Home',
		'home.greeting.0': 'Good morning,',
    	'home.greeting.1': 'Good afternoon,',
    	'home.greeting.2': 'Good evening,',
		'home.friends': 'Your Friends ({0})',
		'home.recent': 'Recent Experiences',
		'home.favourites': 'Your Favourite Experiences',

		'user.join': 'Join {0.displayName} in {1.name}',
		'user.friends': 'Friends ({0})',
		'user.friends.count': 'friends',
		'user.followers': 'followers',
		'user.following': 'following',
		'user.joined': 'Joined {0|time_ago}',
		'user.badges': 'Achievements',
		'user.id': 'User ID:',
		'user.group': 'Primary Group',
		'user.experience_0': 'Unknown Status',
		'user.experience_1': 'Unknown Status',
		'user.experience_2': 'Currently Playing',
		'user.experience_3': 'Currently Editing',
		'user.avatar': 'Currently Wearing',
		'user.talent': '{0}\'s Creator Page',

		'user_role.0': 'Staff',
		'user_role.1': 'Beta Tester',
		'user_role.2': 'Dev Relations',
		'user_role.3': 'Event Organiser',
		'user_role.4': 'This user is banned.',
		'user_role.5': 'svelteblox Contributor',

		'profile.name': 'Display Name',
		'profile.about': 'Bio',
		'profile.about.placeholder': 'Tell the Roblox community about what you like to make, build, and explore...',
		'profile.overview': 'Overview',
		'profile.overview.experiences': 'Favourite Experiences',
		'profile.creations': 'Creations',
		'profile.creations.experiences': 'Pinned Experiences',

		'badge.id': 'Badge ID:',
		'badge.enabled.true': 'Obtainable',
		'badge.enabled.false': 'Unobtainable',
		'badge.given': 'Awarded {0|number} times, {1|number} today',
		'badge.given.none': 'No-one has this achievement yet!',
		'badge.earned': '{0}% of players have this achievement',
		'badge.user_has': 'You have this achievement, good job!',
		'badge.earn_date': 'You earned this {0|time_ago}',
		'badge.earn_date.target': '{0} earned this {1|time_ago}',

		'badge_list': '{0}\'s Achievements',

		'unlock_pin': 'Unlock PIN',
		'unlock_pin.summary': 'You need to enter your four-digit PIN before you can continue.',
		'unlock_pin.placeholder': '1234',
		'unlock_pin.incorrect': 'The PIN you entered is incorrect, please try again.',
		'unlock_pin.ratelimited': 'You are being rate-limited, please try again later.',

		'name_change_result.0': '',
		'name_change_result.1': 'This name has been deemed inappropriate.',
		'name_change_result.2': 'You can only change your name every 7 days.',
		'name_change_result.3': 'Your name must be between 3-20 characters.',

		'talent_status.false': 'Not Open to Work',
		'talent_status.true': 'Open to Work',

		'friends': '{0}\'s Friends ({1})',
		'favourites': '{0}\'s Favourite Experiences ({1})',

		'groups': 'Groups',
		'groups.list': 'Your Groups',

		'group.members': '{0|number} members',
		'group.join': 'Join Group',
		'group.about': 'About',
		'group.experiences': 'Experiences',
		'group.related_groups': 'Affiliates',
		'group.shout': 'Group Shout',
		'group.shout.time': 'Posted {0|time_ago}',
		'group.hover': '{0}\n{1} Member(s)',

		'group.role': 'Your Role: {0}',
		'group.user_role': '{0}\'s Role: {1}',

		'group_entry.true': 'Public',
		'group_entry.false': 'Invite-only',

		'group_relationship.Allies': 'Allies',
		'group_relationship.Enemies': 'Enemies',

		'experience.play': 'Quick Play',
		'experience.play2': 'Play {0}',
		'experience.join_user': 'Join {0??Friend}',
		'experience.playing': '{0|number} users are currently in-experience',
		'experience.playing2': '{0|number} playing',
		'experience.favourite_false': 'Favourite',
		'experience.favourite_true': 'Favourited',
		'experience.rating': '{0}% of players liked this experience',
		'experience.rating2': '{0}% liked this',
		'experience.unrated': 'Unrated',
		'experience.hover': '{0}\n{1|number} Playing',
		'experience.socials': 'Social Links',
		'experience.friend_servers': 'Friend Servers ({0})',
		'experience.private_servers': 'Private Servers ({0})',

		'server.owner': 'Created by {0}',

		'carousel.prev': 'Previous Thumbnail',
		'carousel.next': 'Next Thumbnail',

		'create': 'Create',

		'creator': 'by {0}',
		'created_date': 'Created {0|time_ago}',
		'updated_date': 'Updated {0|time_ago}',

		'user_status.0': 'Offline',
		'user_status.1': 'Online',
		'user_status.2': 'In-experience',
		'user_status.3': 'In-studio',

		'image_status.0': 'Loading',
		'image_status.1': 'This image is currently pending review',
		'image_status.2': 'This image has been removed',
		'image_status.3': 'This image is currently unavailable',

		'theme.dark': 'Dark',
		'theme.light': 'Light',
		'theme.color_purple': 'Purple',

		'locale.en-AU': 'Australian English',
		'locale.lv-LV': 'Latvian',
		'locale.ru-RU': 'Russian',
		'locale.ja-JP': 'Japanese',

		'client_channel.live': 'Default',
		'client_channel.zcanary': 'Canary',
		'client_channel.zintegration': 'Integration',
		'client_channel.zwinplayer64': 'Windows 64-Bit Client',

		'settings': 'Settings',
		'settings.theme': 'Colour Theme',
		'settings.theme.label': 'Themes',
		'settings.locale': 'Language',
		'settings.locale.label': 'Languages',
		'settings.client_channel': 'Client Launch Channel',
		'settings.client_channel.label': 'Deployment Channels',

		'pagination.sort_order': 'Sort by',
		'pagination.sort_direction': 'Sort direction',

		'sort_order.0': 'Name',
		'sort_order.1': 'User Status',

		'sort_direction.0': 'Descending',
		'sort_direction.1': 'Ascending',

		'badge.verified': 'Verified Badge',
		'badge.verified.summary': 'This badge verifies that the holder is a notable and authentic creator, brand, or public figure.',

		'badge.premium': 'Premium Badge',
		'badge.premium.summary': 'This badge indicates that the holder has an active Premium Membership.',

		'social_link.type.Twitch': 'Twitch Channel',
		'social_link.type.Discord': 'Discord Server',
		'social_link.type.Facebook': 'Facebook Profile',
		'social_link.type.Guilded': 'Guilded Server',
		'social_link.type.Twitter': 'Twitter Profile',
		'social_link.type.YouTube': 'YouTube Channel',
		'social_link.type.RobloxGroup': 'Roblox Group',

		'mod_notice.title.Ban 3 Days': 'You have been temporarily banned for 3 days.',
		'mod_notice.reviewed': 'Reviewed {0|time_ago}.',
		'mod_notice.ends': 'You can re-active your account {0|time_in}.',
		'mod_notice.details': 'More Information',
		'mod_notice.guidelines': 'Roblox Community Guidelines',

		'number': '{0|number}',
		'number_small': '{0|number_small}',
		'number_small.0': '{0}K',
		'number_small.1': '{0}M',
		'number_small.2': '{0}B',
		'number_small.3': '{0}T',

		'date_format': 'MMMM D, YYYY [at] h:mm:ss A',

		'time_ago': '{0|time_ago}',
		'time_ago.0_0': '{0} seconds ago',
		'time_ago.0_1': 'now',
		'time_ago.1_0': '{0} minutes ago',
		'time_ago.1_1': '{0} minute ago',
		'time_ago.2_0': '{0} hours ago',
		'time_ago.2_1': '{0} hour ago',
		'time_ago.3_0': '{0} days ago',
		'time_ago.3_1': 'yesterday',
		'time_ago.4_0': '{0} months ago',
		'time_ago.4_1': 'last month',
		'time_ago.5_0': '{0} years ago',
		'time_ago.5_1': 'last year',

		'time_in': '{0|time_in}',
		'time_in.0_0_0': 'in {0} seconds',
		'time_in.0_1_0': 'now',
		'time_in.1_0_0': 'in {0} minutes',
		'time_in.1_1_0': 'in one minute',
		'time_in.2_0_0': 'in {0} hours',
		'time_in.2_1_0': 'in one hour',
		'time_in.3_0_0': 'in {0} days',
		'time_in.3_0_1': 'in {0} days, and {1} hours',
		'time_in.3_0_2': 'in {0} days, and one hour',
		'time_in.3_1_0': 'tomorrow',
		'time_in.4_0_0': 'in {0} months',
		'time_in.4_1_0': 'next month',
		'time_in.5_0_0': 'in {0} years',
		'time_in.5_1_0': 'next year',

		'toast.success': 'Success!',
		'toast.friend_accept': 'You are now friends with <b>{0}</b>.', 
		'toast.friend_decline': 'You have declined <b>{0}</b>\'s friend request.', 
		'toast.friend_request': 'You have sent a friend request to <b>{0}</b>.',
		'toast.friend_removed': 'You have ended your friendship with <b>{0}</b>.',
		'toast.client_join': 'Joining Friend...',
		'toast.client_join2': 'Joining Private Server...',
		'toast.client_play': 'Joining Experience...',
		'toast.client_play2': 'Joining Server...',
		'toast.client_launched': 'The Roblox Player should open in a few seconds.',
		'toast.studio_edit': 'Starting Edit Session...',
		'toast.studio_launched': 'Roblox Studio should open in a few seconds.'
	},
	'ja-JP': {
		'action.copy_id': 'IDをコピー',
		'action.view_all': 'すべて見る',
		'action.show_all': 'すべて表示する',
		'action.copy_link': 'リンクをコピーする',
		'action.edit_studio': 'Studio で編集',
		'action.view_roblox': 'Roblox で見る',
		'action.view_talent': 'Talent Hub で見る',
		'action.view_devforum': 'DevForum で見る',

		'home': '家',
		'home.greeting.0': 'おはよう',
    	'home.greeting.1': 'こんにちは',
    	'home.greeting.2': 'こんばんは',
		'home.friends': 'あなたの友人 ({0})',
		'home.recent': '最近の経験',

		'user.join': '{0} in {1} に参加',
		'user.friends': '友達 ({0})',
		'user.friends.count': '友達',
		'user.followers': 'フォロワー',
		'user.following': '以下',
		'user.favourites': 'お気に入りの体験',
		'user.experience_2': '現在プレイ中',
		'user.experience_3': '現在編集中',
		'user.avatar': '現在着用中',
		'groups': 'グループ',
		'groups.list': 'あなたのグループ',

		'group.members': '{0.memberCount|number} 人のメンバー',
		'group.join': 'グループに参加',
		'group.experiences': 'グループ体験',
		'group.shout': 'グループシャウト',

		'experience.play': 'クイックプレイ',
		'experience.play2': '遊ぶ {0}',
		'experience.join_user': '加入する {0??Friend}',
		'experience.playing2': '{0|number}プレイ',
		'experience.favourite_false': 'お気に入り',
		'experience.favourite_true': 'お気に入り',
		'experience.rating2': '{0}% がこれを気に入りました',
		'experience.unrated': '未評価',
		'experience.hover': '{0}\n{1|number} プレイ中',

		'create': '作成',

		'creator': '作成: {0}',

		'user_status.0': 'オフライン',
		'user_status.1': 'オンライン',
		'user_status.2': 'ある体験で',
		'user_status.3': 'スタジオで',

		'theme.dark': '暗い',
		'theme.light': '灯',
		'theme.color_purple': '紫',

		'client_channel.live': 'デフォルト',
		'client_channel.zcanary': 'カナリア',
		'client_channel.zintegration': '統合化',

		'settings': '設定',
		'settings.theme': 'カラーテーマ',
		'settings.theme.label': 'テーマ',
		'settings.locale': '言語',
		'settings.locale.label': '言語',

		'time_ago.0_0': '{0} 秒前',
		'time_ago.0_1': '今',
		'time_ago.1_0': '{0}分前',
		'time_ago.1_1': '{0}分前',
		'time_ago.2_0': '{0}時間前',
		'time_ago.2_1': '{0}時間前',
		'time_ago.3_0': '{0}日前',
		'time_ago.3_1': '昨日',
		'time_ago.4_0': '{0}ヶ月前',
		'time_ago.4_1': '先月',
		'time_ago.5_0': '{0}年前',
		'time_ago.5_1': '去年',
	}
}