export default {
	'en-AU': {
		'action.copy_id': 'Copy ID',
		'action.view_all': 'View all',
		'action.show_all': 'Show all',
		'action.copy_link': 'Copy Link',
		'action.edit_studio': 'Edit in Studio',
		'action.view_roblox': 'View on Roblox',
		'action.view_talent': 'View on Talent Hub',
		'action.view_devforum': 'View on DevForum',
		'action.copy_place_id': 'Copy Place ID',
		'action.configure_place': 'Configure Place',
		'action.copy_universe_id': 'Copy Experience ID',
		'action.configure_universe': 'Configure Experience',

		'action.friend.0': 'Send Friend Request',
		'action.friend.1': 'Remove Friend',
		'action.friend.2': 'Friend Request Sent',
		'action.friend.3': 'Accept Friend Request',

		'home': 'Home',
		'home.greeting.0': 'Good morning,',
    	'home.greeting.1': 'Good afternoon,',
    	'home.greeting.2': 'Good evening,',
		'home.friends': 'Your Friends ({0})',
		'home.recent': 'Recent Experiences',

		'user.join': 'Join {0.displayName} in {1.name}',
		'user.friends': 'Friends ({0})',
		'user.friends.count': 'friends',
		'user.followers': 'followers',
		'user.following': 'following',
		'user.favourites': 'Favourite Experiences',
		'user.experience_0': 'Unknown Status',
		'user.experience_1': 'Unknown Status',
		'user.experience_2': 'Currently Playing',
		'user.experience_3': 'Currently Editing',
		'user.avatar': 'Currently Wearing',
		'user.role.0': 'ROBLOX STAFF',
		'user.role.1': 'BETA TESTER',
		'user.role.2': 'DEV RELATIONS',
		'user.role.3': 'EVENT ORGANISER',
		'user.talent': '{0}\'s Creator Page',
		
		'talent_status.false': 'Not Open to Work',
		'talent_status.true': 'Open to Work',

		'friends': '{0}\'s Friends ({1})',

		'groups': 'Groups',
		'groups.list': 'Your Groups',

		'group.members': '{0.memberCount|number} members',
		'group.join': 'Join Group',
		'group.about': 'About',
		'group.experiences': 'Experiences',
		'group.related_groups': 'Affiliates',
		'group.shout': 'Group Shout',
		'group.shout.time': 'Posted {0|time_ago}',
		'group.hover': '{0}\n{1} Member(s)',

		'group_relationship.Allies': 'Allies',
		'group_relationship.Enemies': 'Enemies',

		'experience.play': 'Quick Play',
		'experience.play2': 'Play {0}',
		'experience.join_user': 'Join {0??Friend}',
		'experience.playing': '{0|number} users are currently in-experience',
		'experience.playing2': '{0|number} playing',
		'experience.favourite_false': 'Favourite',
		'experience.favourite_true': 'Favourited',
		'experience.rating': '{0}% of players liked this experience',
		'experience.rating2': '{0}% liked this',
		'experience.unrated': 'Unrated',
		'experience.hover': '{0}\n{1|number} Playing',
		'experience.friend_servers': 'Friend Servers ({0})',
		'experience.private_servers': 'Private Servers ({0})',

		'server.owner': 'Created by {0}',

		'carousel.prev': 'Previous Thumbnail',
		'carousel.next': 'Next Thumbnail',

		'create': 'Create',

		'creator': 'by {0}',

		'user_status.0': 'Offline',
		'user_status.1': 'Online',
		'user_status.2': 'In-experience',
		'user_status.3': 'In-studio',

		'image_status.0': 'Loading',
		'image_status.1': 'This image is currently pending review',
		'image_status.2': 'This image has been removed',
		'image_status.3': 'This image is currently unavailable',

		'theme.dark': 'Dark',
		'theme.light': 'Light',
		'theme.color_purple': 'Purple',

		'locale.en-AU': 'Australian English',
		'locale.lv-LV': 'Latvian',
		'locale.ru-RU': 'Russian',
		'locale.ja-JP': 'Japanese',

		'client_channel.LIVE': 'Default',
		'client_channel.zcanary': 'Canary',
		'client_channel.zintegration': 'Integration',
		'client_channel.zwinplayer64': 'Windows 64-Bit Client',

		'settings': 'Settings',
		'settings.theme': 'Colour Theme',
		'settings.theme.label': 'Themes',
		'settings.locale': 'Language',
		'settings.locale.label': 'Languages',
		'settings.client_channel': 'Client Launch Channel',
		'settings.client_channel.label': 'Deployment Channels',

		'pagination.sort_order': 'Sort by',
		'pagination.sort_direction': 'Sort direction',

		'sort_order.0': 'Name',
		'sort_order.1': 'User Status',

		'sort_direction.0': 'Descending',
		'sort_direction.1': 'Ascending',

		'number': '{0|number}',
		'number_small': '{0|number_small}',
		'number_small.0': '{0}K',
		'number_small.1': '{0}M',
		'number_small.2': '{0}B',
		'number_small.3': '{0}T',

		'time_ago': '{0|time_ago}',
		'time_ago.0_0': '{0} seconds ago',
		'time_ago.0_1': 'now',
		'time_ago.1_0': '{0} minutes ago',
		'time_ago.1_1': '{0} minute ago',
		'time_ago.2_0': '{0} hours ago',
		'time_ago.2_1': '{0} hour ago',
		'time_ago.3_0': '{0} days ago',
		'time_ago.3_1': 'yesterday',
		'time_ago.4_0': '{0} months ago',
		'time_ago.4_1': 'last month',
		'time_ago.5_0': '{0} years ago',
		'time_ago.5_1': 'last year',

		'toast.success': 'Success!',
		'toast.friend_accept': 'You are now friends with <b>{0}</b>.', 
		'toast.friend_decline': 'You have declined <b>{0}</b>\'s friend request.', 
		'toast.friend_request': 'You have sent a friend request to <b>{0}</b>.',
		'toast.friend_removed': 'You have ended your friendship with <b>{0}</b>.',
		'toast.client_join': 'Joining Friend...',
		'toast.client_join2': 'Joining Private Server...',
		'toast.client_play': 'Joining Experience...',
		'toast.client_play2': 'Joining Server...',
		'toast.client_launched': 'The Roblox Player should open in a few seconds.',
		'toast.studio_edit': 'Starting Edit Session...',
		'toast.studio_launched': 'Roblox Studio should open in a few seconds.'
	},
	'ja-JP': {
		'action.copy_id': 'IDをコピー',
		'action.view_all': 'すべて見る',
		'action.show_all': 'すべて表示する',
		'action.copy_link': 'リンクをコピーする',
		'action.edit_studio': 'Studio で編集',
		'action.view_roblox': 'Roblox で見る',
		'action.view_talent': 'Talent Hub で見る',
		'action.view_devforum': 'DevForum で見る',

		'home': '家',
		'home.greeting.0': 'おはよう',
    	'home.greeting.1': 'こんにちは',
    	'home.greeting.2': 'こんばんは',
		'home.friends': 'あなたの友人 ({0})',
		'home.recent': '最近の経験',

		'user.join': '{0.displayName} in {1.name} に参加',
		'user.friends': '友達 ({0})',
		'user.friends.count': '友達',
		'user.followers': 'フォロワー',
		'user.following': '以下',
		'user.favourites': 'お気に入りの体験',
		'user.experience_2': '現在プレイ中',
		'user.experience_3': '現在編集中',
		'user.avatar': '現在着用中',
		'user.role.0': 'ROBLOX 職員',
		'user.role.1': 'ベータテスター',
		'user.role.3': 'イベントオーガナイザー',

		'groups': 'グループ',
		'groups.list': 'あなたのグループ',

		'group.members': '{0.memberCount|number} 人のメンバー',
		'group.join': 'グループに参加',
		'group.experiences': 'グループ体験',
		'group.shout': 'グループシャウト',

		'experience.play': 'クイックプレイ',
		'experience.play2': '遊ぶ {0}',
		'experience.join_user': '加入する {0??Friend}',
		'experience.playing2': '{0|number}プレイ',
		'experience.favourite_false': 'お気に入り',
		'experience.favourite_true': 'お気に入り',
		'experience.rating2': '{0}% がこれを気に入りました',
		'experience.unrated': '未評価',
		'experience.hover': '{0}\n{1|number} プレイ中',

		'create': '作成',

		'creator': '作成: {0}',

		'user_status.0': 'オフライン',
		'user_status.1': 'オンライン',
		'user_status.2': 'ある体験で',
		'user_status.3': 'スタジオで',

		'theme.dark': '暗い',
		'theme.light': '灯',
		'theme.color_purple': '紫',

		'client_channel.LIVE': 'デフォルト',
		'client_channel.zcanary': 'カナリア',
		'client_channel.zintegration': '統合化',

		'settings': '設定',
		'settings.theme': 'カラーテーマ',
		'settings.theme.label': 'テーマ',
		'settings.locale': '言語',
		'settings.locale.label': '言語',

		'time_ago.0_0': '{0} 秒前',
		'time_ago.0_1': '今',
		'time_ago.1_0': '{0}分前',
		'time_ago.1_1': '{0}分前',
		'time_ago.2_0': '{0}時間前',
		'time_ago.2_1': '{0}時間前',
		'time_ago.3_0': '{0}日前',
		'time_ago.3_1': '昨日',
		'time_ago.4_0': '{0}ヶ月前',
		'time_ago.4_1': '先月',
		'time_ago.5_0': '{0}年前',
		'time_ago.5_1': '去年',
	}
}